typography_spectrum: 0.7175206909887493
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.18980298563838005
  lightness: 0.21114707877859473
  saturation: 0.1385661163367331
  rhythmicContrast: 0.058277658419683576
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20006536738947034
analytics:
  google: null
  facebook: null
  twitter: null
name: vcio
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Your Virtual CIO
description: Operational Technology Excellence
purpose: []
